const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let loaded,unlocks=0,stops=0,saved='';
const elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{events:{},attributes:{},addEventListener(k,f){this.events[k]=f;},setAttribute(k,v){this.attributes[k]=v;}});return elements.get(id);};
const ctx=vm.createContext({Date,Map,ASSETS:{},apyState:{checkedAt:Date.now()},document:{getElementById:element},window:{addEventListener(k,f){if(k==='load')loaded=f;}},localStorage:{getItem:()=>null,setItem(k,v){saved=v;}},setInterval(){},renderApy(){}});
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../limit-monitor.js'),'utf8'),ctx);
ctx.unlock=()=>{unlocks++;};ctx.stop=()=>{stops++;};
vm.runInContext('unlockLimitAudio=unlock;stopLimitAlarm=stop;',ctx);loaded();
const ids=['alarmBuyGap','alarmBuyRange','alarmSellRange','alarmBuyPosition','alarmSellPosition'];
for(const id of ids)assert.equal(element(id).attributes['aria-pressed'],'false');
const button=element('alarmBuyGap');button.events.click();
assert.equal(button.textContent,'Buy Gap: ON');assert.equal(button.attributes['aria-pressed'],'true');assert.equal(unlocks,1);
assert.equal(element('alarmSellRange').textContent,'Sell Range: OFF');
button.events.click();assert.equal(button.textContent,'Buy Gap: OFF');assert.equal(button.attributes['aria-pressed'],'false');assert.equal(stops,1);
assert.equal(JSON.parse(saved).alarmOptions.buyGap,false);
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
for(const id of ids)assert.match(html,new RegExp(`id="${id}"[^>]+title="[^"]+"`));
assert.equal(elements.has('testLimitAudio'),false);
assert.ok(!html.includes('testLimitAudio'));
console.log('PASS: five independent accessible alarm toggles, hover notes, persistence, audio unlock and stop');
