const assert=require('node:assert/strict');
global.ExponentBook=require('../orderbook');
const {orderWatchKey,orderWatchRecord,validOrderWatch,inspectWatchedOrder}=require('../order-watch');
const now=Math.floor(Date.now()/1000),bookAddress='ndAp6RJ1Q2wkoczCdXQteZk2UMnmDNWQDCCCKyLtymv',vault='y5UFEeB3LfUErLBjDMdZynAoqCwBgsMnDZSzth68aaH';
const owner='3srhDoV9VunGoVGEVNy8NMhkoqeQE8szhN1T2Z6qPgof';
const market={vaultAddress:vault,maturityDateUnixTs:now+10000,orderbookAddresses:[bookAddress]};
const api={orderbook_address:bookAddress,vault_address:vault,user_address:owner,offer_idx:2,order_type:'buyYT',price_implied_apy:65000,
  created_at:new Date((now-100)*1000).toISOString(),expiry_at:new Date((now+1000)*1000).toISOString(),expiry_seconds:1100,original_amount:'500',tx_signature:'test'};
const record=orderWatchRecord(api,market,'sronyc');assert.ok(validOrderWatch(record));
const a={id:1,next:2,pricePointer:1,owner:'another',side:2,virtual:1,created:now-200,expiry:now+1000,amount:100n};
const b={...a,id:2,next:0,owner,virtual:0,created:record.created,expiry:record.expiry,amount:200n};
const high={...a,id:3,next:0,pricePointer:2,amount:100n};
const book={vault,maturity:market.maturityDateUnixTs,priceDecimals:6,
  prices:[{id:1,price:65000,buyHead:1,buyTail:2},{id:2,price:65001,buyHead:3,buyTail:3}],offers:new Map([[1,a],[2,b],[3,high]])};
const snapshot={book,checkedAt:Date.now(),time:now,slot:123};
const inspect=()=>inspectWatchedOrder(record,snapshot,now,true);
assert.equal(inspect().status,'Behind','higher raw price can round to the same APY');
high.amount=0n;assert.equal(inspect().status,'Behind','virtual sellPT before buyYT shares queue');
a.expiry=now-1;assert.equal(inspect().status,'At front');
assert.equal(inspectWatchedOrder(record,snapshot,now).status,'Unverified','production gate must remain closed');
record.verified=true;
b.amount=50n;assert.equal(inspect().status,'At front','partial fill preserves identity');
b.owner='reused';assert.equal(inspect().status,'Inactive');b.owner=owner;
b.created++;assert.equal(inspect().status,'Inactive');b.created--;
b.amount=501n;assert.equal(inspect().status,'Inactive');b.amount=50n;
snapshot.error='offline';assert.equal(inspect().status,'Stale');delete snapshot.error;
snapshot.time=now-40;assert.equal(inspect().status,'Stale');snapshot.time=now;
snapshot.checkedAt=0;assert.equal(inspect().status,'Stale');snapshot.checkedAt=Date.now();
book.vault='wrong';assert.equal(inspect().status,'Unverified');book.vault=vault;
high.next=3;assert.equal(inspect().status,'Unverified','broken higher-price chain blocks classification');high.next=0;
book.offers.set(4,{...b,id:4});assert.equal(inspect().status,'Unverified','detached live offers block classification');book.offers.delete(4);
b.amount=0n;assert.equal(inspect().status,'Inactive');
record.verified=false;assert.equal(inspect().status,'Unverified');
assert.notEqual(orderWatchKey(record),orderWatchKey({...record,created:record.created+1}));
assert.notEqual(orderWatchKey(record),orderWatchKey({...record,signature:'new'}));
assert.notEqual(orderWatchKey(record),orderWatchKey({...record,maturity:record.maturity+1}));
assert.equal(orderWatchRecord({...api,order_type:'sellPT'},market,'sronyc'),null);
assert.equal(orderWatchRecord({...api,original_amount:Number.MAX_SAFE_INTEGER+1},market,'sronyc'),null);
assert.equal(orderWatchRecord({...api,expiry_seconds:2},market,'sronyc'),null);
assert.equal(validOrderWatch({...record,rawPrice:4294967295}),false,'overflow APY cannot break the watch list');
assert.equal(validOrderWatch({...record,original:'9'.repeat(1000)}),false,'oversized stored amounts are rejected');
console.log('PASS: complete buy-side traversal, virtual offers, exact prices, identity reuse, partial fills, stale/corrupt/missing data and release gate');
