const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const maturity=Date.now()/1000+10000,market={vaultAddress:'vault',maturityDateUnixTs:maturity,orderbookAddresses:['book'],impliedApy:.075};
const records=new Map(),entries=new Map(),rangeTypes=[];
const ctx=vm.createContext({Date,Map,Set,Number,Math,ASSETS:{t:{mint:'mint',label:'Token'}},orderWatchState:{records,busy:false},walletMonitor:{wallets:new Set(['wallet'])},limitState:{enabled:true,records:{[JSON.stringify(['vault',maturity])]:{threshold:'0.5'}}},limitAlarm:{entries},apyState:{markets:[market],checkedAt:Date.now()},selectedAssets:new Set(),buyOrderApy:p=>100*Math.expm1(p/1e6),limitKey:m=>JSON.stringify([m.vaultAddress,m.maturityDateUnixTs]),limitNumber:Number,limitGapAtOrBelow:()=>false,farthestApyMarket:()=>market,renderLimitCells(){},renderLimitAlarmRow(){},evaluateLimitAlerts(){},saveOrderWatches(){},apyDate:String,limitRewardRangeCheck:(m,a,t)=>{rangeTypes.push(t);return {outside:false};},startLimitAlarmAudio(){},renderLimitAlarm(){},notifyLimitAlarm(){}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../auto-limit.js'),'utf8'),ctx);const run=s=>vm.runInContext(s,ctx);
const raw=apy=>Math.round(Math.log1p(apy/100)*1e6),base={assetKey:'t',vault:'vault',book:'book',maturity,expiry:maturity,owner:'wallet',checkedAt:Date.now(),status:'Behind',limitEdges:{}};
records.set('buy',{...base,limitEdges:{},rawPrice:raw(7.1),orderSide:'buy'});records.set('sell',{...base,limitEdges:{},rawPrice:raw(7.9),orderSide:'sell'});
assert.equal(run('evaluateAutoLimitAlerts().length'),2,'both directional gaps satisfy 0.5pp');
assert.deepEqual(rangeTypes.sort(),['buyYT','sellYT']);
assert.match([...entries.values()].join('\n'),/Buy/);assert.match([...entries.values()].join('\n'),/Sell/);
entries.clear();records.get('sell').limitEdges={};records.get('sell').rawPrice=raw(8.1);records.get('buy').limitEdges={gap:false,range:false};
assert.equal(run('evaluateAutoLimitAlerts().some(m=>m.startsWith("Sell"))'),false,'sell gap above threshold does not alarm');
console.log('PASS: Buy/Sell labels, reversed Sell gap, shared threshold and sellYT campaign range');
